[project]
name = "admin-panel"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.8",
    "jinja2>=3.1.6",
]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ['admin_panel']

[project.optional-dependencies]
example = [
    "uvicorn>=0.34.0",
]
